name: MGFlyingCars
main: com.comze_instancelabs.mgflyingcars.Main
version: 1.2.0
author: InstanceLabs
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   fc:
      description: Main command
      usage: /fc [action]
      aliases: [flyingcars, mgflyingcars]
