name: MGFlyingCars
main: com.comze_instancelabs.mgflyingcars.Main
version: 1.0.1
author: InstanceLabs
softdepend: [Vault, MinigamesAPI]
depend: [MinigamesAPI]
loadbefore: [MinigamesAPI]
commands:
   fc:
      description: Main command
      usage: /fc [action]
      aliases: [flyingcars, mgflyingcars]
