name: MGFlyingCars
main: com.comze_instancelabs.mgflyingcars.Main
version: ${version}
author: [InstanceLabs,mepeisen]
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   fc:
      description: Main command
      usage: /fc [action]
      aliases: [flyingcars, mgflyingcars, flyc]
